package com.feather.net.packets;

public enum ClientPacket {

	UNKNOWN_PACKET(),
	
	AFK_PACKET(-1),
	ENTER_STRING_PACKET(-1),
	MAGIC_ON_ITEM_PACKET(-1),
	CLICK_PACKET(-1),
	MOVE_MOUSE_PACKET(-1),
	KEY_TYPED_PACKET(-1),
	IN_OUT_SCREEN_PACKET(-1),
	
	GRAND_EXCHANGE_ITEM_SELECT(71),
	ENTER_LONGSTRING_PACKET(48),
	WALKING_PACKET(8),
	MINI_WALKING_PACKET(58),
	ACTION_BUTTON_1_PACKET(14),
	ACTION_BUTTON_2_PACKET(67),
	ACTION_BUTTON_3_PACKET(5),
	ACTION_BUTTON_4_PACKET(55),
	ACTION_BUTTON_5_PACKET(68),
	ACTION_BUTTON_6_PACKET(90),
	ACTION_BUTTON_7_PACKET(6),
	ACTION_BUTTON_8_PACKET(32),
	ACTION_BUTTON_9_PACKET(27),
	ACTION_BUTTON_10_PACKET(96),
	WORLD_MAP_CLICK(38),
	WORLD_LIST_UPDATE(87),
	CLAN_FORUM_THREAD(18),
	CLAN_NAME_AND_MOTTO(48),
	ITEM_EXAMINE(102),
	LOBBY_MAIN_CLICK_PACKET(91),
	LOBBY_FRIEND_CHAT_SETTINGS(79),
	ACTION_BUTTON10_PACKET(96),
	RECEIVE_PACKET_COUNT_PACKET(33),
	PLAYER_OPTION_4_PACKET(17),
	MOVE_CAMERA_PACKET(103),
	INTERFACE_ON_OBJECT(37),
	CLOSE_INTERFACE_PACKET(54),
	COMMANDS_PACKET(60),
	ITEM_ON_ITEM_PACKET(3),
	DONE_LOADING_REGION_PACKET(30),
	PING_PACKET(21),
	SCREEN_PACKET(98),
	CHAT_TYPE_PACKET(83),
	CHAT_PACKET(53),
	PUBLIC_QUICK_CHAT_PACKET(86),
	ADD_FRIEND_PACKET(89),
	ADD_IGNORE_PACKET(4),
	REMOVE_IGNORE_PACKET(73),
	JOIN_FRIEND_CHAT_PACKET(36),
	CHANGE_FRIEND_CHAT_PACKET(22),
	KICK_FRIEND_CHAT_PACKET(74),
	REMOVE_FRIEND_PACKET(24),
	SEND_FRIEND_MESSAGE_PACKET(82),
	SEND_FRIEND_QUICK_CHAT_PACKET(0),
	OBJECT_CLICK_1_PACKET(26),
	OBJECT_CLICK_2_PACKET(59),
	OBJECT_CLICK_3_PACKET(40),
	OBJECT_CLICK_4_PACKET(23),
	OBJECT_CLICK_5_PACKET(80),
	OBJECT_EXAMINE_PACKET(25),
	NPC_CLICK_1_PACKET(31),
	NPC_CLICK_2_PACKET(101),
	NPC_CLICK_3_PACKET(34),
	NPC_CLICK_4_PACKET(65),
	ATTACK_NPC(20),
	PLAYER_OPTION_1_PACKET(42),
	PLAYER_OPTION_2_PACKET(46),
	PLAYER_OPTION_6_PACKET(49),
	PLAYER_OPTION_5_PACKET(77),
	PLAYER_OPTION_7_PACKET(51),
    PLAYER_OPTION_9_PACKET(56),
	ITEM_TAKE_PACKET(57),
	DIALOGUE_CONTINUE_PACKET(72),
	ENTER_INTEGER_PACKET(81),
	ENTER_NAME_PACKET(29),
	SWITCH_INTERFACE_ITEM_PACKET(76),
	INTERFACE_ON_PLAYER(50),
	INTERFACE_ON_NPC(66),
	COLOR_ID_PACKET(97),
	NPC_EXAMINE_PACKET(9),
	REPORT_ABUSE_PACKET(11),
	JOIN_CLAN_CHAT_PACKET(133),
	ENTER_LONG_TEXT_PACKET(48),
    KICK_CLAN_CHAT_PACKET(92),
    GRAND_EXCHANGE_ITEM_SELECT_PACKET(71),
	
	// Possibly Correct?
	MOUSE_PRESSED_PACKET(15),
	MOUSE_RELEASED_PACKET(13),
	WINDOW_FOCUS_PACKET(70),
	KEY_PRESSED_PACKET(1);
	
	
	/**
	 * The value.
	 */
	private final int value;

	/**
	 * Constructs a new {@code ClientPacket} {@code Object}.
	 * 
	 * @param value
	 *            The value.
	 */
	private ClientPacket(int value) {
		this.value = (int) value;
	}

	private ClientPacket() {
		this.value = -1;
	}
	
	/**
	 * Gets the return code value.
	 * 
	 * @return The value.
	 */
	public final int getValue() {
		return value;
	}
	
	public static ClientPacket getPacketFromId(final int id) {
		for(ClientPacket client_packet : ClientPacket.values()) {
			if(id == client_packet.getValue()) {
				return client_packet;
			}
		}
		
		return ClientPacket.UNKNOWN_PACKET;
	}
}
